// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	LoginUserName string `json:"login_user_name"`
	LoginPassWord string `json:"login_pass_word"`
}

type JwtToken struct {
	AccessToken  string `json:"access_token,omitempty"`
	AccessExpire int64  `json:"access_expire,omitempty"`
}

type LoginResponse struct {
	LoginUserName string   `json:"login_user_name"`
	JwtToken      JwtToken `json:"jwt_token"`
}

type RegisterRequest struct {
	RegisterUserName string `json:"register_user_name"`
	RegisterPassWord string `json:"register_pass_word"`
	InviteCode       string `json:"invite_code"`
}

type RegisterResponse struct {
	RegisterUserName string `json:"register_user_name"`
}
